import json
import time
from elasticsearch import Elasticsearch
# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_LOGIN = "elastic"
ELASTIC_PASSWORD = "YGP1ww5oWzuagMHeN7aM"
# Create the client instance
# client = Elasticsearch(
#     "https://192.168.248.130:9200",
#     ca_certs="http_ca.crt",
#     basic_auth=(ELASTIC_LOGIN, ELASTIC_PASSWORD)
# )
client = Elasticsearch(["http://elastic:YGP1ww5oWzuagMHeN7aM@152.136.174.19:9200"], verify_certs=False)
client_info = client.info()
client_info_dict = dict(client_info)
client_info_bigstring = json.dumps(client_info_dict, ensure_ascii=False, indent=4)
print(" client.info(): ", client_info_bigstring)