# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
#llm:
#  api_type: "openai"  # or azure / ollama / groq etc.
#  model: "gpt-3.5-turbo-16k"  # or gpt-3.5-turbo
#  base_url: "https://api.chatgptid.net/v1"  # or forward url / other llm url
#  api_key: "sk-ln0lOOW4xaCLK0nT92367a1852D744E2867d256933B8Bc35"


llm:
  api_type: "ollama"  # or azure / ollama / groq etc.
  model: "qwen:32b-chat-v1.5-q2_K"  # or gpt-3.5-turbo  #codegemma:7b-instruct-v1.1-q6_K ##qwen:32b-chat-v1.5-q2_K
  base_url: "http://127.0.0.1:11434/api"  # or forward url / other llm url